# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 20:08
from __future__ import unicode_literals

import channelsdemo.main.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=channelsdemo.main.models.post_image_name)),
            ],
            options={
                'ordering': ('-created',),
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bumped', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('bumped',),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Thread'),
        ),
    ]
